// src/components/Editor.vue
<template>
    <v-container fill-height justify-center fluid>
        <v-flex ref="editor" class="editor markdown-body" data-testid="editor"></v-flex>
    </v-container>
</template>

<script lang="ts">
import Vue, { PropType } from "vue"
import { debounce } from "lodash"

import { BaseView, ProseMirrorView, MarkdownView } from "@/editor"
import { Note } from "@/controller"
import { isMac } from "@/utils"

const metaKey = isMac() ? "metaKey" : "ctrlKey"

export default Vue.extend({
    name: "Editor",
    props: {
        note: {
            type: Note as PropType<Note>,
            required: true,
        },
    },
    data(): {
        view?: BaseView
        sourceCodeMode: boolean
        update: () => void
    } {
        return {
            view: undefined,
            sourceCodeMode: false,
            update: () => {},
        }
    },
    mounted: function() {
        this.initEditor()
        this.update = debounce(() => {
            console.log("Updating")
            if (this.view) {
                this.note.updateContent(this.view.content)
            }
        }, 1000)
        window.addEventListener("keydown", this.handleKeydown)
    },
    beforeDestroy: function() {
        window.removeEventListener("keydown", this.handleKeydown)
        if (this.view) {
            this.note.updateContent(this.view.content)
            this.view.destroy()
        }
    },
    methods: {
        initEditor: function() {
            const View = this.sourceCodeMode ? MarkdownView : ProseMirrorView
            const content = this.view ? this.view.content : this.note.content
            if (this.view) this.view.destroy()
            try {
                this.view = new View(this.$refs.editor as HTMLElement, content)
            } catch (error) {
                setTimeout(() => alert(`Failed to load markown content:\n${error}`), 0)
            }
            if (this.view) this.view.focus()
        },
        switchEditor: function() {
            this.sourceCodeMode = !this.sourceCodeMode
            this.initEditor()
        },
        handleKeydown: function(event: KeyboardEvent) {
            if (event[metaKey] && event.code === "Slash") {
                console.debug("meta + / has been pressed")
                this.switchEditor()
            } else {
                this.update()
            }
        },
    },
})
</script>

<style lang="scss" scoped>
.editor {
    height: 100%;
    width: 100%;

    display: flex;
    flex-direction: column;
    justify-content: flex-start;
    align-items: stretch;
}
</style>

<style lang="scss">
@import "../../node_modules/github-markdown-css/github-markdown.css";
@import "../style/editor.sass";

// For source code mode
.markdown-body > textarea {
    padding-top: 80px;
    height: 100%;
    overflow: visible;
    font-family: monospace; // Make tables align

    border: none;
    outline: none;
    box-shadow: none;
}

// For WYSIWYG mode
.markdown-body > .ProseMirror {
    padding-left: calc(50% - 512px);
    padding-right: calc(50% - 512px);

    padding-top: 80px;
    flex: 1;

    border: none;
    outline: none;
    box-shadow: none;
}

// Override vuetify's styles
.v-application {
    code {
        color: inherit;
        box-shadow: none;
    }
    code::before {
        content: "";
    }
    code::after {
        content: "";
    }
}
</style>

// src/components/Editor/Editor.tsx
import { BaseView, MarkdownView, ProseMirrorView } from "src/editor"
import { Note } from "src/controller"
import { Theme, createStyles, makeStyles } from "@material-ui/core"
import { debounce } from "lodash"
import { isMac } from "src/utils"
import React from "react"
import clsx from "clsx"

type EditorProps = {
    autoFocus: boolean
    note: Note
    updateRenderKey: () => void
}

type InnerEditorProps = EditorProps & {
    autoFocus: boolean
    note: Note
    updateRenderKey: () => void
    classes: Record<never, string>
}

const useStyles = makeStyles((theme: Theme) => {
    return createStyles({})
})

const metaKey = isMac() ? "metaKey" : "ctrlKey"

class InnerEditor extends React.Component<InnerEditorProps> {
    private editorRef: React.RefObject<HTMLDivElement>
    private view: BaseView | null
    private note: Note
    private update: () => void
    private handleKeydown: (event: KeyboardEvent) => void
    private updateRenderKey: () => void
    private classes: Record<never, string>
    private sourceCodeMode: boolean

    constructor(props: InnerEditorProps) {
        super(props)
        this.editorRef = React.createRef<HTMLDivElement>()
        this.view = null
        this.note = props.note
        this.update = () => {}
        this.handleKeydown = () => {}
        this.updateRenderKey = props.updateRenderKey
        this.classes = props.classes
        this.sourceCodeMode = false
    }

    componentDidMount() {
        this.createView(ProseMirrorView, this.note.content)

        this.update = debounce(() => {
            console.log("Updating")
            if (this.view) {
                this.note.updateContent(this.view.content)
                this.updateRenderKey()
            }
        }, 1000)

        this.handleKeydown = (event: KeyboardEvent) => {
            if (event[metaKey] && event.code === "Slash") {
                console.debug("meta + / has been pressed")
                this.switchView()
            } else {
                this.update()
            }
        }

        window.addEventListener("keydown", this.handleKeydown)
    }

    componentWillUnmount() {
        window.removeEventListener("keydown", this.handleKeydown)
        if (this.view) {
            this.note.updateContent(this.view.content)
            this.view.destroy()
        }
    }

    createView(View: typeof MarkdownView | typeof ProseMirrorView, content: string) {
        if (this.view) this.view.destroy()
        try {
            console.log("creating view")
            const ref = this.editorRef.current
            if (!ref) throw new Error("ref is empty")
            this.view = new View(ref, content)
            this.view.focus()
        } catch (error) {
            setTimeout(() => alert(`Failed to load markown content:\n${error}`), 0)
        }
    }

    switchView() {
        this.sourceCodeMode = !this.sourceCodeMode
        const View = this.sourceCodeMode ? MarkdownView : ProseMirrorView
        const content = this.view?.content || this.note.content
        this.createView(View, content)
    }

    render() {
        return (
            <div
                ref={this.editorRef}
                className={clsx(this.classes, "markdown-body", "editor")}
                data-testid="editor"
            />
        )
    }
}

export const Editor: React.FC<EditorProps> = ({ autoFocus, note, updateRenderKey }) => {
    const classes = useStyles()
    return (
        <InnerEditor
            autoFocus={autoFocus}
            note={note}
            updateRenderKey={updateRenderKey}
            classes={classes}
        />
    )
}
