// packages/app/src/components/Editor.vue
<template>
    <v-container fill-height justify-center fluid>
        <v-flex ref="editor" class="editor markdown-body" @keydown="handleKeydown"></v-flex>
    </v-container>
</template>

<script lang="ts">
import Vue from "vue"
import { BaseView, ProseMirrorView, MarkdownView } from "../../../markdown/src/views"
import { Note } from "../controller"
import { debounce } from "lodash"

export default Vue.extend({
    props: {
        note: {
            type: Note,
            required: true,
        },
    },
    data(): {
        view?: BaseView
        sourceCodeMode: boolean
        update: () => void
    } {
        return {
            view: undefined,
            sourceCodeMode: false,
            update: () => {},
        }
    },
    mounted: function() {
        if (this.view) this.view.destroy()
        let place = this.$refs.editor as HTMLElement
        this.view = new ProseMirrorView(place, this.note.content)
        this.update = debounce(() => {
            console.log("Updating")
            if (this.view) {
                this.note.updateContent(this.view.content)
            }
        }, 1000)
    },
    beforeDestroy: function() {
        if (this.view) {
            this.note.updateContent(this.view.content)
            this.view.destroy()
        }
    },
    methods: {
        switchEditor: function() {
            if (!this.view) return
            this.sourceCodeMode = !this.sourceCodeMode
            let View = this.sourceCodeMode ? MarkdownView : ProseMirrorView
            let content = this.view.content
            this.view.destroy()
            this.view = new View(this.$refs.editor as HTMLElement, content)
            this.view.focus()
        },
        handleKeydown: function(event: KeyboardEvent) {
            if (event.metaKey && event.code === "Slash") {
                console.debug("meta + / has been pressed")
                this.switchEditor()
            } else {
                this.update()
            }
        },
    },
})
</script>

<style lang="scss" scoped>
@import url("../../../../node_modules/github-markdown-css/github-markdown.css");
@import url("../../style/editor.sass");

.editor {
    height: 100%;
    width: 100%;

    display: flex;
    flex-direction: column;
    justify-content: flex-start;
    align-items: stretch;
}
</style>

<style lang="scss">
// For source code mode
.markdown-body > textarea {
    padding-top: 80px;
    height: 100%;
    overflow: visible;

    border: none;
    outline: none;
    box-shadow: none;
}

// For WYSIWYG mode
.markdown-body > .ProseMirror {
    padding-left: calc(50% - 512px);
    padding-right: calc(50% - 512px);

    padding-top: 80px;
    flex: 1;

    border: none;
    outline: none;
    box-shadow: none;
}
</style>

// packages/web/src/editor/components/Editor.tsx
import { createStyles, makeStyles, Theme } from "@material-ui/core"
import { useTheme } from "@material-ui/core/styles"
import clsx from "clsx"
import React, { useEffect, useRef, useState } from "react"

import { MAX_EDITOR_WIDTH } from "src/constants"
import { Note } from "src/controller"
import { SourceCodeEditor, WysiwygEditor } from "src/editor"
import { metaKey } from "src/utils"

const useStyles = makeStyles((theme: Theme) => {
    return createStyles({
        editor: {
            height: "100%",
            width: "100%",
            maxWidth: MAX_EDITOR_WIDTH,
            display: "flex",
            flexDirection: "column",
            justifyContent: "flex-start",
            alignItems: "stretch",
            "& .ProseMirror": {
                paddingTop: "40px !important",
                flex: "1 !important",
                border: "none",
                outline: "none",
                boxShadow: "none",
            },
        },
    })
})

type EditorProps = {
    autoFocus: boolean
    note: Note
    setNoteContent: (content: string) => void
}

export const Editor: React.FC<EditorProps> = ({ autoFocus, note, setNoteContent }) => {
    const classes = useStyles()
    const [mode, setMode] = useState<"source-code" | "wysiwyg" | null>("wysiwyg")
    const initialContent = useRef<string>(note.content)

    useEffect(() => {
        const handleKeydown = (event: KeyboardEvent) => {
            if (event[metaKey] && event.code === "Slash") {
                console.debug(`metaKey + / has been pressed`)
                const nextMode = mode === "wysiwyg" ? "source-code" : "wysiwyg"
                // Unmount SourceCodeEditor / WysiwygEditor first, so that it's `componentWillUnmount` will be called.
                setMode(null)
                setTimeout(() => {
                    initialContent.current = note.content
                    setMode(nextMode)
                }, 0)
            }
        }
        window.addEventListener("keydown", handleKeydown)
        return () => window.removeEventListener("keydown", handleKeydown)
    }, [mode, note])

    useEffect(() => {
        console.debug(`Mounting <${Editor.displayName}/>`)
        return () => console.debug(`Unmounting <${Editor.displayName}/>`)
    }, [])

    const theme = useTheme()
    const className = clsx(
        classes.editor,
        "markdown-body",
        theme.palette.type === "light" ? "markdown-body--light" : "markdown-body--dark",
    )

    if (mode === "source-code")
        return (
            <SourceCodeEditor
                className={className}
                autoFocus={autoFocus}
                editable={!note.deleted}
                content={initialContent.current}
                setContent={setNoteContent}
            />
        )
    else if (mode === "wysiwyg")
        return (
            <WysiwygEditor
                className={className}
                autoFocus={autoFocus}
                editable={!note.deleted}
                content={initialContent.current}
                setContent={setNoteContent}
            />
        )
    else return null
}

Editor.displayName = "Editor"
